/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.MeyerTatianaBarraganAlberto.vista;

import edu.ub.prog2.MeyerTatianaBarraganAlberto.controlador.Controlador;
import static edu.ub.prog2.MeyerTatianaBarraganAlberto.vista.AplicacioUB4.*;
import edu.ub.prog2.utils.AplicacioException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author dragr
 */
public class frmAddFichero extends javax.swing.JDialog {
    
    private final Controlador ctrl;
    private final static String TITLE = "Añadir Fichero";
    private boolean added;
    
    /**
     * Creates new form frmAddFichero
     */
    public frmAddFichero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        added = false;
        this.ctrl = Controlador.getInstance();
        initComponents();
        audioSelected();
        this.setTitle(TITLE);
        this.getRootPane().setDefaultButton(optAceptar);
        
    }

    /**
     * Getter de added, usado para refrescar la biblioteca al cerrar la ventana.
     * @return 
     */
    public boolean isAdded() {
        return added;
    }
    
    
    private void audioSelected(){
        panelAudioImagen.setVisible(true);
        pathText.requestFocus();
        swtVideo.setSelected(false);
    }
    
    private void videoSelected() {
        panelAudioImagen.setVisible(false);
        pathText.requestFocus();
        swtAudio.setSelected(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        swtGroup = new javax.swing.ButtonGroup();
        swtAudio = new javax.swing.JRadioButton();
        swtVideo = new javax.swing.JRadioButton();
        panelPath = new javax.swing.JPanel();
        abrir = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        pathText = new java.awt.TextField();
        panelAudioImagen = new javax.swing.JPanel();
        abrir1 = new javax.swing.JButton();
        nombre1 = new javax.swing.JLabel();
        pathTextImagen = new java.awt.TextField();
        optAceptar = new javax.swing.JButton();
        optCancelar = new javax.swing.JButton();
        panelNombre = new javax.swing.JPanel();
        nombre2 = new javax.swing.JLabel();
        nameText = new java.awt.TextField();

        swtGroup.add(swtAudio);
        swtGroup.add(swtVideo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        swtAudio.setSelected(true);
        swtAudio.setText("Audio");
        swtAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swtAudioActionPerformed(evt);
            }
        });

        swtVideo.setText("Vídeo");
        swtVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swtVideoActionPerformed(evt);
            }
        });

        abrir.setText("...");
        abrir.setMaximumSize(new java.awt.Dimension(60, 20));
        abrir.setMinimumSize(new java.awt.Dimension(60, 20));
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });

        nombre.setText("Fichero");

        pathText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPathLayout = new javax.swing.GroupLayout(panelPath);
        panelPath.setLayout(panelPathLayout);
        panelPathLayout.setHorizontalGroup(
            panelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPathLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(nombre)
                .addGap(14, 14, 14)
                .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelPathLayout.setVerticalGroup(
            panelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPathLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre)
                    .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        abrir1.setText("...");
        abrir1.setMaximumSize(new java.awt.Dimension(60, 20));
        abrir1.setMinimumSize(new java.awt.Dimension(60, 20));
        abrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrir1ActionPerformed(evt);
            }
        });

        nombre1.setText("Imagen");

        pathTextImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAudioImagenLayout = new javax.swing.GroupLayout(panelAudioImagen);
        panelAudioImagen.setLayout(panelAudioImagenLayout);
        panelAudioImagenLayout.setHorizontalGroup(
            panelAudioImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAudioImagenLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(nombre1)
                .addGap(14, 14, 14)
                .addComponent(pathTextImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(abrir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panelAudioImagenLayout.setVerticalGroup(
            panelAudioImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAudioImagenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAudioImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre1)
                    .addComponent(pathTextImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(panelAudioImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abrir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optAceptar.setText("Aceptar");
        optAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAceptarActionPerformed(evt);
            }
        });

        optCancelar.setText("Cancelar");
        optCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCancelarActionPerformed(evt);
            }
        });

        nombre2.setText("Nombre");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNombreLayout = new javax.swing.GroupLayout(panelNombre);
        panelNombre.setLayout(panelNombreLayout);
        panelNombreLayout.setHorizontalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(nombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panelNombreLayout.setVerticalGroup(
            panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNombreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(swtAudio)
                            .addComponent(swtVideo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAudioImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPath, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAudioImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(optAceptar)
                            .addComponent(optCancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(swtAudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swtVideo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pathTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        String path = fileChooserPath();
        if (!path.isEmpty()) {
            this.pathText.setText(path);
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void abrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir1ActionPerformed
        String path = fileChooserPath();
        if (!path.isEmpty()) {
            this.pathTextImagen.setText(path);
        }
    }//GEN-LAST:event_abrir1ActionPerformed

    private void pathTextImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextImagenActionPerformed

    private void optCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_optCancelarActionPerformed

    private void optAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAceptarActionPerformed
        String path = pathText.getText();
        String name = nameText.getText();
        String codec = "";
        float duracion = 0;
        
        try{
            if(swtAudio.isSelected()){
                String imagePath = pathTextImagen.getText();
                int kbps = 0;
                ctrl.afegirAudio(path, imagePath, name, codec, duracion, kbps);
            } else{
                float fps = 0;
                int amplada = 0;
                int alcada = 0;
                ctrl.afegirVideo(path, name, codec, duracion, alcada, amplada, fps);
            }
            JOptionPane.showMessageDialog(this, "Fichero " + name + " añadido", "Fichero añadido", JOptionPane.PLAIN_MESSAGE, GUT_IMG);
            added = true;
            this.dispose();
        } catch (AplicacioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.PLAIN_MESSAGE, ERROR_IMG);
        }
    }//GEN-LAST:event_optAceptarActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void swtAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swtAudioActionPerformed
       audioSelected();
    }//GEN-LAST:event_swtAudioActionPerformed

    private void swtVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swtVideoActionPerformed
        videoSelected();
    }//GEN-LAST:event_swtVideoActionPerformed
    
    /**
     * Devuelve el String del path absoluto del fichero seleccionado
     *
     * @return String
     */
    private String fileChooserPath() {
        String path = "";
        JFileChooser fileChooser = new JFileChooser();
        int resultat = fileChooser.showOpenDialog(this);
        if (resultat == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            path = file.getAbsolutePath();
        }
        return path;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAddFichero dialog = new frmAddFichero(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton abrir1;
    private java.awt.TextField nameText;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JButton optAceptar;
    private javax.swing.JButton optCancelar;
    private javax.swing.JPanel panelAudioImagen;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPath;
    private java.awt.TextField pathText;
    private java.awt.TextField pathTextImagen;
    private javax.swing.JRadioButton swtAudio;
    private javax.swing.ButtonGroup swtGroup;
    private javax.swing.JRadioButton swtVideo;
    // End of variables declaration//GEN-END:variables
}
